# Generated by Django 4.1.3 on 2023-03-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default='', max_length=50)),
                ('prod_price', models.CharField(default='', max_length=50)),
                ('prod_tag', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
