# Generated by Django 4.1.3 on 2023-03-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
