# Generated by Django 4.2 on 2023-04-18 09:50

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_product_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='product/', verbose_name='Photo'),
        ),
    ]
