# Generated by Django 4.2 on 2023-04-19 05:00

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_prod_image_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_back',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='product/', verbose_name='product_image_back'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_left',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='product/', verbose_name='product_image_left'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_right',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='product/', verbose_name='product_image_right'),
        ),
    ]
