# Generated by Django 4.2 on 2023-04-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_product_product_image_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
