# Generated by Django 4.2 on 2023-04-19 05:15

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='product/', verbose_name='Photo'),
        ),
    ]
